/** Keys owned by NutriForge client state (localStorage). Keep in sync with index.html usage. */
export const NF_BACKUP_SCHEMA = 'nutriforge-backup';
export const NF_BACKUP_VERSION = 1;

/** Safe profile ids generated by the app (`p` + digits). */
export const NF_PROFILE_ID_RE = /^p\d+$/;

export const NF_BACKUP_KEYS = [
  'nf_diary',
  'nf_diary_by_profile',
  'nf_diary_goals',
  'nf_profiles',
  'nf_active_profile',
  'nf_favourites',
  'nf_plate',
  'nf_saved_plates',
  'nf_meal_plates',
  'nf_today_focus',
  'nf_portions',
  'nf_chat',
  'nf_view',
  'nf_darkmode',
  'nf_community_start_done',
];

/**
 * @param {(key: string) => string | null} getItem
 * @returns {Record<string, string>}
 */
export function collectBackupKeys(getItem) {
  const keys = {};
  for (const k of NF_BACKUP_KEYS) {
    let v;
    try {
      v = getItem(k);
    } catch {
      v = null;
    }
    if (v != null && v !== '') keys[k] = v;
  }
  return keys;
}

/**
 * @param {(key: string) => string | null} getItem
 * @param {Record<string, unknown>} [meta]
 */
export function buildBackupDocument(getItem, meta = {}) {
  return {
    schema: NF_BACKUP_SCHEMA,
    version: NF_BACKUP_VERSION,
    exportedAt: new Date().toISOString(),
    app: 'nutriforge-africa',
    keys: collectBackupKeys(getItem),
    ...meta,
  };
}

/**
 * @param {unknown} raw
 * @returns {unknown[]}
 */
export function sanitizeProfilesPayload(raw) {
  let list = raw;
  if (typeof raw === 'string') {
    try {
      list = JSON.parse(raw);
    } catch {
      return [];
    }
  }
  if (!Array.isArray(list)) return [];
  const out = [];
  for (const item of list) {
    if (!item || typeof item !== 'object') continue;
    const id = typeof item.id === 'string' ? item.id.trim() : '';
    if (!NF_PROFILE_ID_RE.test(id)) continue;
    const name = typeof item.name === 'string' ? item.name.trim().slice(0, 120) : '';
    if (!name) continue;
    const clean = { ...item, id, name };
    if (typeof clean.note === 'string') clean.note = clean.note.slice(0, 280);
    out.push(clean);
  }
  return out;
}

/**
 * @param {Record<string, unknown>} keys
 * @returns {Record<string, string>}
 */
export function sanitizeBackupKeys(keys) {
  const next = { ...keys };
  if (typeof next.nf_profiles === 'string') {
    try {
      next.nf_profiles = JSON.stringify(sanitizeProfilesPayload(next.nf_profiles));
    } catch {
      delete next.nf_profiles;
    }
  }
  if (typeof next.nf_active_profile === 'string') {
    const active = next.nf_active_profile.trim();
    if (!NF_PROFILE_ID_RE.test(active)) delete next.nf_active_profile;
    else next.nf_active_profile = active;
  }
  return /** @type {Record<string, string>} */ (next);
}

export function validateBackupDocument(doc) {
  if (!doc || typeof doc !== 'object') return false;
  if (doc.schema !== NF_BACKUP_SCHEMA) return false;
  if (typeof doc.keys !== 'object' || doc.keys === null || Array.isArray(doc.keys)) return false;
  return true;
}

/**
 * @param {Record<string, unknown>} keysPayload
 * @param {(key: string, value: string) => void} setItem
 * @param {(key: string) => void} removeItem
 * @param {{ mode?: 'replace' | 'merge' }} [opts]
 */
export function applyBackupKeys(keysPayload, setItem, removeItem, opts = {}) {
  const mode = opts.mode === 'merge' ? 'merge' : 'replace';
  if (mode === 'replace') {
    for (const k of NF_BACKUP_KEYS) {
      try {
        removeItem(k);
      } catch {
        /* ignore */
      }
    }
  }
  const safePayload = sanitizeBackupKeys(keysPayload);
  for (const [k, val] of Object.entries(safePayload)) {
    if (!NF_BACKUP_KEYS.includes(k)) continue;
    if (typeof val !== 'string') continue;
    try {
      setItem(k, val);
    } catch {
      /* ignore */
    }
  }
}
