var plannerAnchor=plannerDateKey(new Date()),weeklyPlan={},plannerSources=[];
function plannerStorageKey(){return 'nf_weekly_plan_'+(activeProfileId||'personal');}
function loadWeeklyPlan(){
  weeklyPlan={};try{var saved=JSON.parse(localStorage.getItem(plannerStorageKey())||'{}');
    Object.keys(saved).forEach(function(date){if(!plannerWeek(date).length)return;['breakfast','lunch','dinner'].forEach(function(meal){var slot=saved[date]&&saved[date][meal];if(!slot||!Array.isArray(slot.items))return;var portions={};slot.items.forEach(function(p){portions[p.id]=p.grams;});var clean=plannerSnapshot(slot.items.map(function(p){return p.id;}),portions,foodsById,slot.name);if(clean){if(!weeklyPlan[date])weeklyPlan[date]={};weeklyPlan[date][meal]=clean;}});});
  }catch(e){}
}
function storeWeeklyPlan(next){try{localStorage.setItem(plannerStorageKey(),JSON.stringify(next));weeklyPlan=next;return true;}catch(e){document.getElementById('plannerStatus').textContent='Could not save. Browser storage may be full or unavailable.';return false;}}
function buildPlannerDrawer(){
  loadWeeklyPlan();loadSavedPlates();
  return '<section class="weekly-planner"><h2>A week of meals, made yours.</h2><p>Save your current plate, reuse a saved plate, or copy a meal already planned. Planning does not log food to your diary.</p><p class="planner-scope">'+safeHtml(activeProfileId?'Client plan: '+((getProfileById(activeProfileId)||{}).name||'Active client'):'Your personal plan')+' · Stored in this browser</p><div class="planner-week-nav"><button type="button" class="ca-btn" onclick="shiftPlannerWeek(-7)" aria-label="Previous week">←</button><label>Week containing<input id="plannerWeek" type="date" value="'+plannerAnchor+'" onchange="changePlannerWeek(this.value)"></label><button type="button" class="ca-btn" onclick="shiftPlannerWeek(7)" aria-label="Next week">→</button></div><form class="planner-compose" onsubmit="event.preventDefault();savePlannedMeal()"><h3>Plan a meal</h3><div class="planner-two"><label>Day<select id="plannerDay"></select></label><label>Meal<select id="plannerMeal"><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select></label></div><label>Plate to use<select id="plannerSource" onchange="plannerSourceChanged()"></select></label><label>Meal name<input id="plannerName" maxlength="60" placeholder="e.g. Beans and greens"></label><p id="plannerReplaceNote" class="swap-note">Saving replaces any meal in the selected slot.</p><button type="submit" class="ca-btn swap-action">Save to this week</button><button type="button" class="ca-btn" onclick="openDrawer(\'plate\')">Build or edit my plate →</button></form><p id="plannerStatus" role="status" aria-live="polite"></p><p class="swap-note">Load plate replaces your current My Plate with the planned meal. Save your current plate first if you want to keep it.</p><p id="plannerProgress" role="status"></p><div id="plannerDays"></div></section>';
}
function plannerSourceChanged(){var option=plannerSources[Number(document.getElementById('plannerSource').value)];document.getElementById('plannerName').value=option?option.name:'';}
function renderPlanner(){
  var days=plannerWeek(plannerAnchor);if(!days.length)return;
  var daySelect=document.getElementById('plannerDay'),previous=daySelect.value;
  daySelect.innerHTML=days.map(function(date){return '<option value="'+date+'">'+safeHtml(plannerDayLabel(date))+'</option>';}).join('');if(days.includes(previous))daySelect.value=previous;else if(days.includes(plannerAnchor))daySelect.value=plannerAnchor;
  var current=plannerSnapshot(Object.keys(plateMap),portionSizes,foodsById,'My current plate');plannerSources=[current];
  var opts='<option value="0" '+(!current?'disabled':'')+'>Current plate'+(!current?' (empty)':'')+'</option>';
  savedPlates.forEach(function(sp){var snapshot=plannerSnapshot(sp.ids,sp.portions||{},foodsById,sp.name);if(snapshot){plannerSources.push(snapshot);opts+='<option value="'+(plannerSources.length-1)+'">Saved: '+safeHtml(sp.name)+'</option>';}});
  Object.keys(weeklyPlan).sort().forEach(function(date){['breakfast','lunch','dinner'].forEach(function(meal){var slot=weeklyPlan[date][meal];if(slot){plannerSources.push(slot);opts+='<option value="'+(plannerSources.length-1)+'">Copy '+date+' '+meal+': '+safeHtml(slot.name)+'</option>';}});});
  document.getElementById('plannerSource').innerHTML=opts;
  if(!current&&plannerSources.length>1)document.getElementById('plannerSource').value='1';plannerSourceChanged();
  var filled=0;
  document.getElementById('plannerDays').innerHTML=days.map(function(date){return '<article class="planner-day"><h3>'+safeHtml(plannerDayLabel(date))+'</h3>'+['breakfast','lunch','dinner'].map(function(meal){var slot=(weeklyPlan[date]||{})[meal];if(slot)filled++;
    return '<div class="planner-slot"><div><span class="planner-meal-label">'+meal+'</span><strong>'+safeHtml(slot?slot.name:'Not planned')+'</strong>'+(slot?'<small>'+slot.items.length+' foods · '+Math.round(slot.items.reduce(function(total,p){return total+foodsById[p.id].kcal*p.grams/100;},0))+' kcal</small>':'')+'</div><div class="planner-slot-actions">'+(slot?'<button type="button" class="ca-btn" onclick="loadPlannedMeal(\''+date+'\',\''+meal+'\')" aria-label="Load '+date+' '+meal+' into My Plate, replacing current plate">Load plate</button><button type="button" class="ca-btn" onclick="removePlannedMeal(\''+date+'\',\''+meal+'\')" aria-label="Remove '+date+' '+meal+'">Remove</button>':'<button type="button" class="ca-btn" onclick="choosePlannerSlot(\''+date+'\',\''+meal+'\')" aria-label="Plan '+date+' '+meal+'">+ Plan</button>')+'</div></div>';}).join('')+'</article>';}).join('');
  document.getElementById('plannerProgress').textContent=filled+' of 21 meals planned this week.';
}
function plannerDayLabel(date){var p=date.split('-');return new Date(+p[0],+p[1]-1,+p[2],12).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});}
function choosePlannerSlot(date,meal){document.getElementById('plannerDay').value=date;document.getElementById('plannerMeal').value=meal;document.getElementById('plannerSource').focus();document.querySelector('.planner-compose').scrollIntoView({block:'start',behavior:'smooth'});}
function changePlannerWeek(date){if(!plannerWeek(date).length)return;plannerAnchor=date;renderPlanner();}
function shiftPlannerWeek(delta){var p=plannerAnchor.split('-'),d=new Date(+p[0],+p[1]-1,+p[2],12);d.setDate(d.getDate()+delta);plannerAnchor=plannerDateKey(d);document.getElementById('plannerWeek').value=plannerAnchor;renderPlanner();}
function savePlannedMeal(){var source=plannerSources[Number(document.getElementById('plannerSource').value)];if(!source){document.getElementById('plannerStatus').textContent='Build a plate first, or choose a saved plate.';return;}var date=document.getElementById('plannerDay').value,meal=document.getElementById('plannerMeal').value;var snapshot=JSON.parse(JSON.stringify(source));snapshot.name=document.getElementById('plannerName').value.trim()||source.name;var next=plannerPut(weeklyPlan,date,meal,snapshot);if(next&&storeWeeklyPlan(next)){renderPlanner();document.getElementById('plannerStatus').textContent='Saved '+snapshot.name+' for '+plannerDayLabel(date)+' '+meal+'.';}}
function removePlannedMeal(date,meal){var next=JSON.parse(JSON.stringify(weeklyPlan));delete next[date][meal];if(storeWeeklyPlan(next)){renderPlanner();document.getElementById('plannerStatus').textContent='Meal removed from the plan.';}}
function loadPlannedMeal(date,meal){var slot=(weeklyPlan[date]||{})[meal];if(!slot)return;plateMap={};slot.items.forEach(function(p){plateMap[p.id]=foodsById[p.id];portionSizes[p.id]=p.grams;});savePersistence();render();openDrawer('plate');}
