var plannerAnchor=plannerDateKey(new Date()),weeklyPlan={},plannerSources=[],plannerCombinationDraft=null;
function plannerStorageKey(){return 'nf_weekly_plan_'+(activeProfileId||'personal');}
function loadWeeklyPlan(){
  weeklyPlan={};try{var saved=JSON.parse(localStorage.getItem(plannerStorageKey())||'{}');
    Object.keys(saved).forEach(function(date){if(!plannerWeek(date).length)return;['breakfast','lunch','dinner'].forEach(function(meal){var slot=saved[date]&&saved[date][meal];if(!slot||!Array.isArray(slot.items))return;var portions={};slot.items.forEach(function(p){portions[p.id]=p.grams;});var clean=plannerSnapshot(slot.items.map(function(p){return p.id;}),portions,foodsById,slot.name);if(clean){if(!weeklyPlan[date])weeklyPlan[date]={};weeklyPlan[date][meal]=clean;}});});
  }catch(e){}
}
function storeWeeklyPlan(next){try{localStorage.setItem(plannerStorageKey(),JSON.stringify(next));weeklyPlan=next;return true;}catch(e){document.getElementById('plannerStatus').textContent='Could not save. Browser storage may be full or unavailable.';return false;}}
function buildPlannerDrawer(){
  loadWeeklyPlan();loadSavedPlates();
  return '<section class="weekly-planner"><h2>A week of meals, made yours.</h2><p>Save your current plate, reuse a saved plate, or copy a meal already planned. Planning does not log food to your diary.</p><p class="planner-scope">'+safeHtml(activeProfileId?'Client plan: '+((getProfileById(activeProfileId)||{}).name||'Active client'):'Your personal plan')+' · Stored in this browser</p><div class="planner-week-nav"><button type="button" class="ca-btn" onclick="shiftPlannerWeek(-7)" aria-label="Previous week">←</button><label>Week containing<input id="plannerWeek" type="date" value="'+plannerAnchor+'" onchange="changePlannerWeek(this.value)"></label><button type="button" class="ca-btn" onclick="shiftPlannerWeek(7)" aria-label="Next week">→</button></div><details class="planner-shopping"><summary>Shopping list <span id="shoppingCount"></span></summary><div id="plannerShopping"></div></details><form class="planner-compose" onsubmit="event.preventDefault();savePlannedMeal()"><h3>Plan a meal</h3><div class="planner-two"><label>Day<select id="plannerDay" onchange="updatePlannerTarget()"></select></label><label>Meal<select id="plannerMeal" onchange="updatePlannerTarget()"><option value="breakfast">Breakfast</option><option value="lunch">Lunch</option><option value="dinner">Dinner</option></select></label></div><label>Meal to use<select id="plannerSource" onchange="plannerSourceChanged()"></select></label><div id="plannerSourcePreview" class="planner-source-preview"></div><label>Meal name<input id="plannerName" maxlength="60" placeholder="e.g. Beans and greens"></label><p id="plannerReplaceNote" class="swap-note">Saving replaces any meal in the selected slot.</p><button id="plannerSaveButton" type="submit" class="ca-btn swap-action">Save to this week</button><button type="button" class="ca-btn" onclick="openDrawer(\'plate\')">Build or edit my plate →</button></form><p id="plannerStatus" role="status" aria-live="polite"></p><p class="swap-note">Load plate replaces your current My Plate with the planned meal. Save your current plate first if you want to keep it.</p><p id="plannerProgress" role="status"></p><div id="plannerDays"></div></section>';
}
function plannerSourceChanged(){var option=plannerSources[Number(document.getElementById('plannerSource').value)];document.getElementById('plannerName').value=option?option.name:'';var preview=document.getElementById('plannerSourcePreview');if(preview)preview.innerHTML=option?'<strong>'+safeHtml(option.name)+'</strong><ul>'+option.items.map(function(p){return '<li>'+safeHtml(foodsById[p.id].name)+' · '+p.grams+' g</li>';}).join('')+'</ul>':'';updatePlannerTarget();}
function renderPlanner(){
  var days=plannerWeek(plannerAnchor);if(!days.length)return;
  var daySelect=document.getElementById('plannerDay'),previous=daySelect.value;
  daySelect.innerHTML=days.map(function(date){return '<option value="'+date+'">'+safeHtml(plannerDayLabel(date))+'</option>';}).join('');if(days.includes(previous))daySelect.value=previous;else if(days.includes(plannerAnchor))daySelect.value=plannerAnchor;
  var current=plannerSnapshot(Object.keys(plateMap),portionSizes,foodsById,'My current plate');plannerSources=[current];
  var opts='<option value="0" '+(!current?'disabled':'')+'>Current plate'+(!current?' (empty)':'')+'</option>';
  var draftIndex=-1;if(plannerCombinationDraft && plannerCombinationDraft.profile===(activeProfileId||'personal')){draftIndex=plannerSources.length;plannerSources.push(plannerCombinationDraft.snapshot);opts+='<option value="'+draftIndex+'">Combination: '+safeHtml(plannerCombinationDraft.snapshot.name)+'</option>';}
  savedPlates.forEach(function(sp){var snapshot=plannerSnapshot(sp.ids,sp.portions||{},foodsById,sp.name);if(snapshot){plannerSources.push(snapshot);opts+='<option value="'+(plannerSources.length-1)+'">Saved: '+safeHtml(sp.name)+'</option>';}});
  Object.keys(weeklyPlan).sort().forEach(function(date){['breakfast','lunch','dinner'].forEach(function(meal){var slot=weeklyPlan[date][meal];if(slot){plannerSources.push(slot);opts+='<option value="'+(plannerSources.length-1)+'">Copy '+date+' '+meal+': '+safeHtml(slot.name)+'</option>';}});});
  document.getElementById('plannerSource').innerHTML=opts;
  if(draftIndex>=0)document.getElementById('plannerSource').value=String(draftIndex);else if(!current&&plannerSources.length>1)document.getElementById('plannerSource').value='1';plannerSourceChanged();
  var filled=0;
  document.getElementById('plannerDays').innerHTML=days.map(function(date){return '<article class="planner-day"><h3>'+safeHtml(plannerDayLabel(date))+'</h3>'+['breakfast','lunch','dinner'].map(function(meal){var slot=(weeklyPlan[date]||{})[meal];if(slot)filled++;
    return '<div class="planner-slot"><div><span class="planner-meal-label">'+meal+'</span><strong>'+safeHtml(slot?slot.name:'Not planned')+'</strong>'+(slot?'<small>'+slot.items.length+' foods · '+Math.round(slot.items.reduce(function(total,p){return total+foodsById[p.id].kcal*p.grams/100;},0))+' kcal</small>':'')+'</div><div class="planner-slot-actions">'+(slot?'<button type="button" class="ca-btn" onclick="loadPlannedMeal(\''+date+'\',\''+meal+'\')" aria-label="Load '+date+' '+meal+' into My Plate, replacing current plate">Load plate</button><button type="button" class="ca-btn" onclick="removePlannedMeal(\''+date+'\',\''+meal+'\')" aria-label="Remove '+date+' '+meal+'">Remove</button>':'<button type="button" class="ca-btn" onclick="choosePlannerSlot(\''+date+'\',\''+meal+'\')" aria-label="Plan '+date+' '+meal+'">+ Plan</button>')+'</div></div>';}).join('')+'</article>';}).join('');
  document.getElementById('plannerProgress').textContent=filled+' of 21 meals planned this week.';
  renderPlannerShopping();
}
function plannerDayLabel(date){var p=date.split('-');return new Date(+p[0],+p[1]-1,+p[2],12).toLocaleDateString(undefined,{weekday:'short',month:'short',day:'numeric'});}
function choosePlannerSlot(date,meal){document.getElementById('plannerDay').value=date;document.getElementById('plannerMeal').value=meal;updatePlannerTarget();document.getElementById('plannerSource').focus();document.querySelector('.planner-compose').scrollIntoView({block:'start',behavior:'smooth'});}
function changePlannerWeek(date){if(!plannerWeek(date).length)return;plannerAnchor=date;renderPlanner();}
function shiftPlannerWeek(delta){var p=plannerAnchor.split('-'),d=new Date(+p[0],+p[1]-1,+p[2],12);d.setDate(d.getDate()+delta);plannerAnchor=plannerDateKey(d);document.getElementById('plannerWeek').value=plannerAnchor;renderPlanner();}
function savePlannedMeal(){var source=plannerSources[Number(document.getElementById('plannerSource').value)];if(!source){document.getElementById('plannerStatus').textContent='Build a plate first, or choose a saved plate.';return;}var date=document.getElementById('plannerDay').value,meal=document.getElementById('plannerMeal').value;var snapshot=JSON.parse(JSON.stringify(source));snapshot.name=document.getElementById('plannerName').value.trim()||source.name;var next=plannerPut(weeklyPlan,date,meal,snapshot);if(next&&storeWeeklyPlan(next)){renderPlanner();document.getElementById('plannerStatus').textContent='Saved '+snapshot.name+' for '+plannerDayLabel(date)+' '+meal+'.';}}
function removePlannedMeal(date,meal){var next=JSON.parse(JSON.stringify(weeklyPlan));delete next[date][meal];if(storeWeeklyPlan(next)){renderPlanner();document.getElementById('plannerStatus').textContent='Meal removed from the plan.';}}
function loadPlannedMeal(date,meal){var slot=(weeklyPlan[date]||{})[meal];if(!slot)return;plateMap={};slot.items.forEach(function(p){plateMap[p.id]=foodsById[p.id];portionSizes[p.id]=p.grams;});savePersistence();render();openDrawer('plate');}

function plannerShoppingKey(){return 'nf_shopping_'+(activeProfileId||'personal')+'_'+plannerWeek(plannerAnchor)[0];}
function plannerShoppingChecks(){try{var value=JSON.parse(localStorage.getItem(plannerShoppingKey())||'{}');return value&&typeof value==='object'?value:{};}catch(e){return {};}}
function renderPlannerShopping(){
  var items=plannerShoppingList(weeklyPlan,plannerAnchor,foodsById),checks=plannerShoppingChecks(),done=items.filter(function(item){return plannerShoppingChecked(item,checks);}).length;
  document.getElementById('shoppingCount').textContent=items.length?' · '+done+'/'+items.length+' ready':'';
  document.getElementById('plannerShopping').innerHTML='<p>For '+safeHtml(plannerDayLabel(plannerWeek(plannerAnchor)[0]))+' – '+safeHtml(plannerDayLabel(plannerWeek(plannerAnchor)[6]))+'. Repeated foods are combined.</p>'+(items.length?'<p class="swap-note">Amounts are planned food weights, including cooked foods and complete dishes. Adjust raw quantities and recipe ingredients before shopping. Changed totals become unchecked.</p><ul class="shopping-items">'+items.map(function(item){var checked=plannerShoppingChecked(item,checks);return '<li><label><input type="checkbox" '+(checked?'checked':'')+' onchange="togglePlannerShopping('+item.id+',this.checked)"><span><strong>'+safeHtml(item.name)+'</strong><small>'+item.meals+' planned meal'+(item.meals===1?'':'s')+'</small></span><b>'+item.grams+' g</b></label></li>';}).join('')+'</ul><div class="shopping-actions"><button type="button" class="ca-btn" onclick="downloadPlannerShopping()">Download list</button></div>':'<p class="shopping-empty">Plan your first meal below to create this week’s shopping list.</p>')+'<p id="shoppingStatus" role="status" aria-live="polite"></p>';
}
function togglePlannerShopping(id,checked){
  var item=plannerShoppingList(weeklyPlan,plannerAnchor,foodsById).find(function(row){return row.id===id;});if(!item)return;
  var checks=plannerShoppingChecks();if(checked)checks[id]=item.grams;else delete checks[id];
  try{localStorage.setItem(plannerShoppingKey(),JSON.stringify(checks));renderPlannerShopping();document.querySelector('#plannerShopping input[onchange^="togglePlannerShopping('+id+',"]').focus();}catch(e){renderPlannerShopping();document.getElementById('shoppingStatus').textContent='Could not save your checkmark. Browser storage may be unavailable.';}
}
function downloadPlannerShopping(){
  var items=plannerShoppingList(weeklyPlan,plannerAnchor,foodsById),checks=plannerShoppingChecks();if(!items.length)return;
  var week=plannerWeek(plannerAnchor),text='NutriForge shopping list\n'+week[0]+' to '+week[6]+'\n\n'+items.map(function(item){return (plannerShoppingChecked(item,checks)?'[x] ':'[ ] ')+item.name+' — '+item.grams+' g';}).join('\n')+'\n\nPlanned food weights; cooked foods and complete dishes are not raw ingredient quantities. Adjust before shopping.\n';
  var url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='nutriforge-shopping-'+week[0]+'.txt';document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(url);},1000);document.getElementById('shoppingStatus').textContent='Shopping list download started.';
}

function updatePlannerTarget(){
 var day=document.getElementById('plannerDay'),meal=document.getElementById('plannerMeal');if(!day||!meal)return;
 var slot=(weeklyPlan[day.value]||{})[meal.value];
 document.getElementById('plannerReplaceNote').textContent=slot?'This will replace “'+slot.name+'” in this slot.':'This slot is empty. Saving does not change your plate or diary.';
 document.getElementById('plannerSaveButton').textContent=slot?'Replace planned meal':'Save to weekly planner';
}
