import { afterEach, expect, it, vi } from 'vitest';
import chat from '../api/chat.js';
import session from '../api/protocol-session.js';
import guide from '../api/protocol-guide.js';
import pdf from '../api/protocol-pdf.js';
function response(){return {code:200,headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(body){this.body=body;return this},send(body){this.body=body;return this},end(){return this}}}
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals()});
it('reports missing AI configuration without an upstream call',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','');const r=response();await chat({method:'POST',body:{}},r);expect(r.code).toBe(503)});
it('forwards multi-turn chat to the provider',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','synthetic-test-key');const fetch=vi.fn(async()=>({ok:true,text:async()=>JSON.stringify({content:[{text:'Synthetic reply'}]})}));vi.stubGlobal('fetch',fetch);const messages=[{role:'user',content:'First question'},{role:'assistant',content:'First answer'},{role:'user',content:'Follow-up'}];const r=response();await chat({method:'POST',body:{messages}},r);expect(JSON.parse(fetch.mock.calls[0][1].body).messages).toEqual(messages);expect(r.code).toBe(200)});
it('rejects invalid chat roles',async()=>{vi.stubEnv('ANTHROPIC_API_KEY','synthetic-test-key');const r=response();await chat({method:'POST',body:{messages:[{role:'system',content:'No'}]}},r);expect(r.code).toBe(400)});
it('keeps protocol documents gated and accepts a signed session',async()=>{vi.stubEnv('PROTOCOL_PASSPHRASE','synthetic-passphrase');vi.stubEnv('PROTOCOL_COOKIE_SECRET','synthetic-cookie-secret-for-tests');vi.stubEnv('VERCEL','1');const denied=response();await guide({method:'GET',headers:{}},denied);expect(denied.code).toBe(403);const wrong=response();await session({method:'POST',body:{passphrase:'wrong'}},wrong);expect(wrong.code).toBe(401);const r=response();await session({method:'POST',body:{passphrase:'synthetic-passphrase'}},r);expect(r.code).toBe(200);expect(r.headers['Set-Cookie']).toContain('HttpOnly');expect(r.headers['Set-Cookie']).toContain('Secure');const headers={cookie:r.headers['Set-Cookie'].split(';')[0]};const html=response();await guide({method:'GET',headers},html);expect(html.code).toBe(200);const file=response();await pdf({method:'HEAD',headers},file);expect(file.code).toBe(200);expect(file.headers['Content-Type']).toBe('application/pdf');expect(Number(file.headers['Content-Length'])).toBeGreaterThan(0)});
